name:                AOC2020
version:             0.1.0.0
github:              "b1g3ar5/AOC2020"
license:             BSD3
author:              "Nick Straw"
maintainer:          "nick@broxholme.com"
copyright:           "N J Straw"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/b1g3ar5/AOC2020#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- Clever
- split
- mtl
- comonad
- finite-typelits
- sort
- containers
- tasty
- tasty-quickcheck
- tasty-hunit
- data-fix
- megaparsec
- semirings
- hashable
- timeit

library:
  source-dirs: src

executables:
  AOC2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2020

tests:
  AOC2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2020
